export enum InputEvent {
  Backward = 'backward',
  Upward = 'upward',
  Forward = 'forward',
  Downward = 'downward',
  Lowpunch = 'lowpunch',
  Highpunch = 'highpunch',
  Block = 'block',
  Run = 'run',
  Lowkick = 'lowkick',
  Highkick = 'highkick',
  Select = 'select',
  Start = 'start',
  Test = 'test',
}
